// Auto-generated by tools/extract_mc_assets.py - DO NOT EDIT MANUALLY
// Forwards to mc_core unified HUD atlas definitions
#pragma once

#include "mc/hud_atlas.hpp"

namespace sekiro::hud {

using ::mc::hud::HudUV;
using ::mc::hud::kUV_CROSSHAIR;
using ::mc::hud::kUV_HEART_CONTAINER;
using ::mc::hud::kUV_HEART_FULL;
using ::mc::hud::kUV_HEART_HALF;
using ::mc::hud::kUV_HUNGER_CONTAINER;
using ::mc::hud::kUV_HUNGER_FULL;
using ::mc::hud::kUV_HUNGER_HALF;
using ::mc::hud::kUV_HOTBAR;
using ::mc::hud::kUV_HOTBAR_SELECTION;
using ::mc::hud::kUV_ITEM_DIAMOND_SWORD;
using ::mc::hud::kUV_ITEM_DIAMOND_PICKAXE;
using ::mc::hud::kUV_ITEM_DIRT;
using ::mc::hud::kUV_ITEM_STONE;
using ::mc::hud::kUV_ITEM_TNT;
using ::mc::hud::kUV_ITEM_GOLDEN_APPLE;
using ::mc::hud::kUV_ITEM_BOW;
using ::mc::hud::kUV_ITEM_ELYTRA;
using ::mc::hud::kUV_ITEM_TOTEM_OF_UNDYING;
using ::mc::hud::kUV_HEART_ABSORB_FULL;
using ::mc::hud::kUV_HEART_ABSORB_HALF;
using ::mc::hud::kUV_PARTICLE_CRIT;
using ::mc::hud::kUV_PARTICLE_DAMAGE;
using ::mc::hud::kUV_PARTICLE_SWEEP_0;
using ::mc::hud::kUV_PARTICLE_SWEEP_1;
using ::mc::hud::kUV_PARTICLE_SWEEP_2;
using ::mc::hud::kUV_PARTICLE_SWEEP_3;
using ::mc::hud::kUV_PARTICLE_SWEEP_4;
using ::mc::hud::kUV_PARTICLE_SWEEP_5;
using ::mc::hud::kUV_PARTICLE_SWEEP_6;
using ::mc::hud::kUV_PARTICLE_SWEEP_7;
using ::mc::hud::kUV_ITEM_ARROW;
using ::mc::hud::kUV_ITEM_TRIDENT;
using ::mc::hud::kUV_ITEM_FLINT_AND_STEEL;
using ::mc::hud::kUV_ITEM_ENDER_PEARL;
using ::mc::hud::kUV_ITEM_ENCHANTED_GOLDEN_APPLE;
using ::mc::hud::kUV_ITEM_BREAD;
using ::mc::hud::kUV_ITEM_COOKED_BEEF;
using ::mc::hud::kUV_ITEM_FIREWORK_ROCKET;
using ::mc::hud::kUV_CONTAINER_TOP;
using ::mc::hud::kUV_CONTAINER_BOTTOM;
using ::mc::hud::kUV_BLOCK_DIRT;
using ::mc::hud::kUV_BLOCK_STONE;
using ::mc::hud::kUV_BLOCK_TNT_TOP;
using ::mc::hud::kUV_BLOCK_TNT_SIDE;
using ::mc::hud::kUV_BLOCK_TNT_BOTTOM;
using ::mc::hud::kUV_HEART_CONTAINER_BLINKING;
using ::mc::hud::kUV_HEART_FULL_BLINKING;
using ::mc::hud::kUV_HEART_HALF_BLINKING;
using ::mc::hud::kUV_XP_BAR_BACKGROUND;
using ::mc::hud::kUV_XP_BAR_PROGRESS;
using ::mc::hud::kUV_ITEM_ZOMBIE_SPAWN_EGG;
using ::mc::hud::kUV_ITEMS;
using ::mc::hud::kHudAtlasWidth;
using ::mc::hud::kHudAtlasHeight;
using ::mc::hud::kHudAtlasPngSize;
using ::mc::hud::kHudAtlasPngData;

} // namespace sekiro::hud
