// Auto-generated by tools/extract_mc_assets.py - DO NOT EDIT MANUALLY
// Forwards to mc_core unified HUD atlas definitions
#pragma once

#include "mc/hud_atlas.hpp"

namespace sekiro::hud {

using ::mc::hud::HudUV;
using ::mc::hud::kUV_CROSSHAIR;
using ::mc::hud::kUV_HEART_CONTAINER;
using ::mc::hud::kUV_HEART_FULL;
using ::mc::hud::kUV_HEART_HALF;
using ::mc::hud::kUV_HUNGER_CONTAINER;
using ::mc::hud::kUV_HUNGER_FULL;
using ::mc::hud::kUV_HUNGER_HALF;
using ::mc::hud::kUV_HOTBAR;
using ::mc::hud::kUV_HOTBAR_SELECTION;
using ::mc::hud::kUV_ITEM_DIAMOND_SWORD;
using ::mc::hud::kUV_ITEM_DIAMOND_PICKAXE;
using ::mc::hud::kUV_ITEM_DIRT;
using ::mc::hud::kUV_ITEM_STONE;
using ::mc::hud::kUV_ITEM_TNT;
using ::mc::hud::kUV_ITEM_GOLDEN_APPLE;
using ::mc::hud::kUV_ITEM_BOW;
using ::mc::hud::kUV_ITEM_ELYTRA;
using ::mc::hud::kUV_ITEM_TOTEM_OF_UNDYING;
using ::mc::hud::kUV_ITEMS;
using ::mc::hud::kHudAtlasWidth;
using ::mc::hud::kHudAtlasHeight;
using ::mc::hud::kHudAtlasPngSize;
using ::mc::hud::kHudAtlasPngData;

} // namespace sekiro::hud
